### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by antoine-gallix** [PyCQA/pycodestyle#828]
Is there a planned date for a new release of pycodestyle? [This issue](https://github.com/PyCQA/pycodestyle/issues/753) for example has been fixed last april, and yet still present on the main release. For direct use of the linter, one can always use the latest master, but it gets complicated to choose pycodestyle version when using it through flake8. It's even worse when using it through even more layers of code, like for example using [pre-commit](https://github.com/pre-commit/pre-commit-hooks). For example, in our project, we use pre-commit to run black formatter, and then flake8. Black and current flake8-pycodestyle disagree on E252 in function signature with type annotation and we had to silence errors to be able to commit. And as a more general question, what is the release policy of this package?

**Comment by asottile** [comment]
We can probably coordinate with the planned pyflakes + flake8 release happening in https://github.com/PyCQA/pyflakes/pull/412

At the very least someone would need to put together the changelog for pycodestyle

P.S. with `pre-commit` you can use a git revision of `pycodestyle` using `additional_dependencies`.

For instance:

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            'git+https://github.com/pycqa/pycodestyle@9f8240e5',
        ]
```
